version: '3'

services:
  go:
    image: 393710905303.dkr.ecr.eu-central-1.amazonaws.com/danutblaj:latest
    environment:
      - 'DB_HOSTNAME=<insert your rds endpoint here>'
      - 'DB_USERNAME=DevOps'
      - 'DB_PASSWORD=DevOps'
      - 'DB_DATABASE=DevOps'
    ports:
      - 8080:80
